// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type Client, type TDataShape, urlSearchParamsBodySerializer } from './client';
import type { PostApiV1LoginAccessTokenData, PostApiV1LoginAccessTokenResponses, PostApiV1LoginAccessTokenErrors, PostApiV1LoginTestTokenData, PostApiV1LoginTestTokenResponses, PostApiV1PasswordRecoveryByEmailData, PostApiV1PasswordRecoveryByEmailResponses, PostApiV1PasswordRecoveryByEmailErrors, PostApiV1ResetPasswordData, PostApiV1ResetPasswordResponses, PostApiV1ResetPasswordErrors, PostApiV1PasswordRecoveryHtmlContentByEmailData, PostApiV1PasswordRecoveryHtmlContentByEmailResponses, PostApiV1PasswordRecoveryHtmlContentByEmailErrors, GetApiV1UsersData, GetApiV1UsersResponses, GetApiV1UsersErrors, PostApiV1UsersData, PostApiV1UsersResponses, PostApiV1UsersErrors, DeleteApiV1UsersMeData, DeleteApiV1UsersMeResponses, GetApiV1UsersMeData, GetApiV1UsersMeResponses, PatchApiV1UsersMeData, PatchApiV1UsersMeResponses, PatchApiV1UsersMeErrors, PatchApiV1UsersMePasswordData, PatchApiV1UsersMePasswordResponses, PatchApiV1UsersMePasswordErrors, PostApiV1UsersSignupData, PostApiV1UsersSignupResponses, PostApiV1UsersSignupErrors, DeleteApiV1UsersByUserIdData, DeleteApiV1UsersByUserIdResponses, DeleteApiV1UsersByUserIdErrors, GetApiV1UsersByUserIdData, GetApiV1UsersByUserIdResponses, GetApiV1UsersByUserIdErrors, PatchApiV1UsersByUserIdData, PatchApiV1UsersByUserIdResponses, PatchApiV1UsersByUserIdErrors, PostApiV1UtilsTestEmailData, PostApiV1UtilsTestEmailResponses, PostApiV1UtilsTestEmailErrors, GetApiV1UtilsHealthCheckData, GetApiV1UtilsHealthCheckResponses, GetApiV1ItemsData, GetApiV1ItemsResponses, GetApiV1ItemsErrors, PostApiV1ItemsData, PostApiV1ItemsResponses, PostApiV1ItemsErrors, DeleteApiV1ItemsByIdData, DeleteApiV1ItemsByIdResponses, DeleteApiV1ItemsByIdErrors, GetApiV1ItemsByIdData, GetApiV1ItemsByIdResponses, GetApiV1ItemsByIdErrors, PutApiV1ItemsByIdData, PutApiV1ItemsByIdResponses, PutApiV1ItemsByIdErrors, PostApiV1PrivateUsersData, PostApiV1PrivateUsersResponses, PostApiV1PrivateUsersErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static postApiV1LoginAccessToken<ThrowOnError extends boolean = false>(options: Options<PostApiV1LoginAccessTokenData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1LoginAccessTokenResponses, PostApiV1LoginAccessTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     */
    public static postApiV1LoginTestToken<ThrowOnError extends boolean = false>(options?: Options<PostApiV1LoginTestTokenData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiV1LoginTestTokenResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     */
    public static postApiV1PasswordRecoveryByEmail<ThrowOnError extends boolean = false>(options: Options<PostApiV1PasswordRecoveryByEmailData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1PasswordRecoveryByEmailResponses, PostApiV1PasswordRecoveryByEmailErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/password-recovery/{email}',
            ...options
        });
    }
    
    /**
     * Reset Password
     * Reset password
     */
    public static postApiV1ResetPassword<ThrowOnError extends boolean = false>(options: Options<PostApiV1ResetPasswordData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1ResetPasswordResponses, PostApiV1ResetPasswordErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/reset-password/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     */
    public static postApiV1PasswordRecoveryHtmlContentByEmail<ThrowOnError extends boolean = false>(options: Options<PostApiV1PasswordRecoveryHtmlContentByEmailData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1PasswordRecoveryHtmlContentByEmailResponses, PostApiV1PasswordRecoveryHtmlContentByEmailErrors, ThrowOnError>({
            responseType: 'text',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/password-recovery-html-content/{email}',
            ...options
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     */
    public static getApiV1Users<ThrowOnError extends boolean = false>(options?: Options<GetApiV1UsersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1UsersResponses, GetApiV1UsersErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options
        });
    }
    
    /**
     * Create User
     * Create new user.
     */
    public static postApiV1Users<ThrowOnError extends boolean = false>(options: Options<PostApiV1UsersData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1UsersResponses, PostApiV1UsersErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     */
    public static deleteApiV1UsersMe<ThrowOnError extends boolean = false>(options?: Options<DeleteApiV1UsersMeData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteApiV1UsersMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     */
    public static getApiV1UsersMe<ThrowOnError extends boolean = false>(options?: Options<GetApiV1UsersMeData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1UsersMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     */
    public static patchApiV1UsersMe<ThrowOnError extends boolean = false>(options: Options<PatchApiV1UsersMeData, ThrowOnError>) {
        return (options.client ?? client).patch<PatchApiV1UsersMeResponses, PatchApiV1UsersMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     */
    public static patchApiV1UsersMePassword<ThrowOnError extends boolean = false>(options: Options<PatchApiV1UsersMePasswordData, ThrowOnError>) {
        return (options.client ?? client).patch<PatchApiV1UsersMePasswordResponses, PatchApiV1UsersMePasswordErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     */
    public static postApiV1UsersSignup<ThrowOnError extends boolean = false>(options: Options<PostApiV1UsersSignupData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1UsersSignupResponses, PostApiV1UsersSignupErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/users/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     */
    public static deleteApiV1UsersByUserId<ThrowOnError extends boolean = false>(options: Options<DeleteApiV1UsersByUserIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteApiV1UsersByUserIdResponses, DeleteApiV1UsersByUserIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     */
    public static getApiV1UsersByUserId<ThrowOnError extends boolean = false>(options: Options<GetApiV1UsersByUserIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiV1UsersByUserIdResponses, GetApiV1UsersByUserIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     * Update a user.
     */
    public static patchApiV1UsersByUserId<ThrowOnError extends boolean = false>(options: Options<PatchApiV1UsersByUserIdData, ThrowOnError>) {
        return (options.client ?? client).patch<PatchApiV1UsersByUserIdResponses, PatchApiV1UsersByUserIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     */
    public static postApiV1UtilsTestEmail<ThrowOnError extends boolean = false>(options: Options<PostApiV1UtilsTestEmailData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1UtilsTestEmailResponses, PostApiV1UtilsTestEmailErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/utils/test-email/',
            ...options
        });
    }
    
    /**
     * Health Check
     */
    public static getApiV1UtilsHealthCheck<ThrowOnError extends boolean = false>(options?: Options<GetApiV1UtilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1UtilsHealthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/utils/health-check/',
            ...options
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     */
    public static getApiV1Items<ThrowOnError extends boolean = false>(options?: Options<GetApiV1ItemsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiV1ItemsResponses, GetApiV1ItemsErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/',
            ...options
        });
    }
    
    /**
     * Create Item
     * Create new item.
     */
    public static postApiV1Items<ThrowOnError extends boolean = false>(options: Options<PostApiV1ItemsData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1ItemsResponses, PostApiV1ItemsErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     */
    public static deleteApiV1ItemsById<ThrowOnError extends boolean = false>(options: Options<DeleteApiV1ItemsByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteApiV1ItemsByIdResponses, DeleteApiV1ItemsByIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     */
    public static getApiV1ItemsById<ThrowOnError extends boolean = false>(options: Options<GetApiV1ItemsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiV1ItemsByIdResponses, GetApiV1ItemsByIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Update Item
     * Update an item.
     */
    public static putApiV1ItemsById<ThrowOnError extends boolean = false>(options: Options<PutApiV1ItemsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutApiV1ItemsByIdResponses, PutApiV1ItemsByIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     */
    public static postApiV1PrivateUsers<ThrowOnError extends boolean = false>(options: Options<PostApiV1PrivateUsersData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiV1PrivateUsersResponses, PostApiV1PrivateUsersErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/private/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
