// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_documents-process_multiple_documents
 */
export type BodyDocumentsProcessMultipleDocuments = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    /**
     * Course Id
     */
    course_id: string;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CourseCreate
 */
export type CourseCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CoursePublic
 */
export type CoursePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * CourseUpdate
 */
export type CourseUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CourseWithDocuments
 */
export type CourseWithDocuments = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Documents
     */
    documents?: Array<DocumentPublic>;
};

/**
 * CoursesPublic
 */
export type CoursesPublic = {
    /**
     * Data
     */
    data: Array<CoursePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Document
 */
export type Document = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Chunk Count
     */
    chunk_count?: number | null;
    /**
     * Course Id
     */
    course_id: string;
    /**
     * Embedding Namespace
     */
    embedding_namespace?: string | null;
    /**
     * Filename
     */
    filename: string;
    status?: DocumentStatus;
    /**
     * Uploaded At
     */
    uploaded_at?: string;
};

/**
 * DocumentPublic
 */
export type DocumentPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
    /**
     * Course Id
     */
    course_id: string;
    /**
     * Uploaded At
     */
    uploaded_at: string;
    status: DocumentStatus;
};

/**
 * DocumentStatus
 */
export type DocumentStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type PostApiV1LoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type PostApiV1LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LoginAccessTokenError = PostApiV1LoginAccessTokenErrors[keyof PostApiV1LoginAccessTokenErrors];

export type PostApiV1LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type PostApiV1LoginAccessTokenResponse = PostApiV1LoginAccessTokenResponses[keyof PostApiV1LoginAccessTokenResponses];

export type PostApiV1LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type PostApiV1LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1LoginTestTokenResponse = PostApiV1LoginTestTokenResponses[keyof PostApiV1LoginTestTokenResponses];

export type PostApiV1PasswordRecoveryByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type PostApiV1PasswordRecoveryByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PasswordRecoveryByEmailError = PostApiV1PasswordRecoveryByEmailErrors[keyof PostApiV1PasswordRecoveryByEmailErrors];

export type PostApiV1PasswordRecoveryByEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostApiV1PasswordRecoveryByEmailResponse = PostApiV1PasswordRecoveryByEmailResponses[keyof PostApiV1PasswordRecoveryByEmailResponses];

export type PostApiV1ResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type PostApiV1ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ResetPasswordError = PostApiV1ResetPasswordErrors[keyof PostApiV1ResetPasswordErrors];

export type PostApiV1ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostApiV1ResetPasswordResponse = PostApiV1ResetPasswordResponses[keyof PostApiV1ResetPasswordResponses];

export type PostApiV1PasswordRecoveryHtmlContentByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailError = PostApiV1PasswordRecoveryHtmlContentByEmailErrors[keyof PostApiV1PasswordRecoveryHtmlContentByEmailErrors];

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponse = PostApiV1PasswordRecoveryHtmlContentByEmailResponses[keyof PostApiV1PasswordRecoveryHtmlContentByEmailResponses];

export type GetApiV1UsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type GetApiV1UsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1UsersError = GetApiV1UsersErrors[keyof GetApiV1UsersErrors];

export type GetApiV1UsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type GetApiV1UsersResponse = GetApiV1UsersResponses[keyof GetApiV1UsersResponses];

export type PostApiV1UsersData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type PostApiV1UsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1UsersError = PostApiV1UsersErrors[keyof PostApiV1UsersErrors];

export type PostApiV1UsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1UsersResponse = PostApiV1UsersResponses[keyof PostApiV1UsersResponses];

export type DeleteApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1UsersMeResponse = DeleteApiV1UsersMeResponses[keyof DeleteApiV1UsersMeResponses];

export type GetApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetApiV1UsersMeResponse = GetApiV1UsersMeResponses[keyof GetApiV1UsersMeResponses];

export type PatchApiV1UsersMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type PatchApiV1UsersMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersMeError = PatchApiV1UsersMeErrors[keyof PatchApiV1UsersMeErrors];

export type PatchApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchApiV1UsersMeResponse = PatchApiV1UsersMeResponses[keyof PatchApiV1UsersMeResponses];

export type PatchApiV1UsersMePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type PatchApiV1UsersMePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersMePasswordError = PatchApiV1UsersMePasswordErrors[keyof PatchApiV1UsersMePasswordErrors];

export type PatchApiV1UsersMePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PatchApiV1UsersMePasswordResponse = PatchApiV1UsersMePasswordResponses[keyof PatchApiV1UsersMePasswordResponses];

export type PostApiV1UsersSignupData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type PostApiV1UsersSignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1UsersSignupError = PostApiV1UsersSignupErrors[keyof PostApiV1UsersSignupErrors];

export type PostApiV1UsersSignupResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1UsersSignupResponse = PostApiV1UsersSignupResponses[keyof PostApiV1UsersSignupResponses];

export type DeleteApiV1UsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1UsersByUserIdError = DeleteApiV1UsersByUserIdErrors[keyof DeleteApiV1UsersByUserIdErrors];

export type DeleteApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1UsersByUserIdResponse = DeleteApiV1UsersByUserIdResponses[keyof DeleteApiV1UsersByUserIdResponses];

export type GetApiV1UsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1UsersByUserIdError = GetApiV1UsersByUserIdErrors[keyof GetApiV1UsersByUserIdErrors];

export type GetApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetApiV1UsersByUserIdResponse = GetApiV1UsersByUserIdResponses[keyof GetApiV1UsersByUserIdResponses];

export type PatchApiV1UsersByUserIdData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type PatchApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersByUserIdError = PatchApiV1UsersByUserIdErrors[keyof PatchApiV1UsersByUserIdErrors];

export type PatchApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchApiV1UsersByUserIdResponse = PatchApiV1UsersByUserIdResponses[keyof PatchApiV1UsersByUserIdResponses];

export type PostApiV1UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type PostApiV1UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1UtilsTestEmailError = PostApiV1UtilsTestEmailErrors[keyof PostApiV1UtilsTestEmailErrors];

export type PostApiV1UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type PostApiV1UtilsTestEmailResponse = PostApiV1UtilsTestEmailResponses[keyof PostApiV1UtilsTestEmailResponses];

export type GetApiV1UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type GetApiV1UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type GetApiV1UtilsHealthCheckResponse = GetApiV1UtilsHealthCheckResponses[keyof GetApiV1UtilsHealthCheckResponses];

export type GetApiV1ItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type GetApiV1ItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ItemsError = GetApiV1ItemsErrors[keyof GetApiV1ItemsErrors];

export type GetApiV1ItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type GetApiV1ItemsResponse = GetApiV1ItemsResponses[keyof GetApiV1ItemsResponses];

export type PostApiV1ItemsData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type PostApiV1ItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ItemsError = PostApiV1ItemsErrors[keyof PostApiV1ItemsErrors];

export type PostApiV1ItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type PostApiV1ItemsResponse = PostApiV1ItemsResponses[keyof PostApiV1ItemsResponses];

export type DeleteApiV1ItemsByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type DeleteApiV1ItemsByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1ItemsByIdError = DeleteApiV1ItemsByIdErrors[keyof DeleteApiV1ItemsByIdErrors];

export type DeleteApiV1ItemsByIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1ItemsByIdResponse = DeleteApiV1ItemsByIdResponses[keyof DeleteApiV1ItemsByIdResponses];

export type GetApiV1ItemsByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type GetApiV1ItemsByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ItemsByIdError = GetApiV1ItemsByIdErrors[keyof GetApiV1ItemsByIdErrors];

export type GetApiV1ItemsByIdResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type GetApiV1ItemsByIdResponse = GetApiV1ItemsByIdResponses[keyof GetApiV1ItemsByIdResponses];

export type PutApiV1ItemsByIdData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type PutApiV1ItemsByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1ItemsByIdError = PutApiV1ItemsByIdErrors[keyof PutApiV1ItemsByIdErrors];

export type PutApiV1ItemsByIdResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type PutApiV1ItemsByIdResponse = PutApiV1ItemsByIdResponses[keyof PutApiV1ItemsByIdResponses];

export type GetApiV1CoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/courses/';
};

export type GetApiV1CoursesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CoursesError = GetApiV1CoursesErrors[keyof GetApiV1CoursesErrors];

export type GetApiV1CoursesResponses = {
    /**
     * Successful Response
     */
    200: CoursesPublic;
};

export type GetApiV1CoursesResponse = GetApiV1CoursesResponses[keyof GetApiV1CoursesResponses];

export type PostApiV1CoursesData = {
    body: CourseCreate;
    path?: never;
    query?: never;
    url: '/api/v1/courses/';
};

export type PostApiV1CoursesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CoursesError = PostApiV1CoursesErrors[keyof PostApiV1CoursesErrors];

export type PostApiV1CoursesResponses = {
    /**
     * Successful Response
     */
    200: CoursePublic;
};

export type PostApiV1CoursesResponse = PostApiV1CoursesResponses[keyof PostApiV1CoursesResponses];

export type DeleteApiV1CoursesByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type DeleteApiV1CoursesByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1CoursesByIdError = DeleteApiV1CoursesByIdErrors[keyof DeleteApiV1CoursesByIdErrors];

export type DeleteApiV1CoursesByIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1CoursesByIdResponse = DeleteApiV1CoursesByIdResponses[keyof DeleteApiV1CoursesByIdResponses];

export type GetApiV1CoursesByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type GetApiV1CoursesByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CoursesByIdError = GetApiV1CoursesByIdErrors[keyof GetApiV1CoursesByIdErrors];

export type GetApiV1CoursesByIdResponses = {
    /**
     * Successful Response
     */
    200: CourseWithDocuments;
};

export type GetApiV1CoursesByIdResponse = GetApiV1CoursesByIdResponses[keyof GetApiV1CoursesByIdResponses];

export type PutApiV1CoursesByIdData = {
    body: CourseUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type PutApiV1CoursesByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1CoursesByIdError = PutApiV1CoursesByIdErrors[keyof PutApiV1CoursesByIdErrors];

export type PutApiV1CoursesByIdResponses = {
    /**
     * Successful Response
     */
    200: CoursePublic;
};

export type PutApiV1CoursesByIdResponse = PutApiV1CoursesByIdResponses[keyof PutApiV1CoursesByIdResponses];

export type GetApiV1CoursesByCourseIdDocumentsData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/courses/{course_id}/documents';
};

export type GetApiV1CoursesByCourseIdDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CoursesByCourseIdDocumentsError = GetApiV1CoursesByCourseIdDocumentsErrors[keyof GetApiV1CoursesByCourseIdDocumentsErrors];

export type GetApiV1CoursesByCourseIdDocumentsResponses = {
    /**
     * Response Courses-List Documents
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetApiV1CoursesByCourseIdDocumentsResponse = GetApiV1CoursesByCourseIdDocumentsResponses[keyof GetApiV1CoursesByCourseIdDocumentsResponses];

export type PostApiV1DocumentsProcessData = {
    body: BodyDocumentsProcessMultipleDocuments;
    path?: never;
    query?: never;
    url: '/api/v1/documents/process';
};

export type PostApiV1DocumentsProcessErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1DocumentsProcessError = PostApiV1DocumentsProcessErrors[keyof PostApiV1DocumentsProcessErrors];

export type PostApiV1DocumentsProcessResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1DocumentsByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/documents/{id}';
};

export type GetApiV1DocumentsByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1DocumentsByIdError = GetApiV1DocumentsByIdErrors[keyof GetApiV1DocumentsByIdErrors];

export type GetApiV1DocumentsByIdResponses = {
    /**
     * Successful Response
     */
    200: Document;
};

export type GetApiV1DocumentsByIdResponse = GetApiV1DocumentsByIdResponses[keyof GetApiV1DocumentsByIdResponses];

export type PostApiV1PrivateUsersData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PostApiV1PrivateUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PrivateUsersError = PostApiV1PrivateUsersErrors[keyof PostApiV1PrivateUsersErrors];

export type PostApiV1PrivateUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1PrivateUsersResponse = PostApiV1PrivateUsersResponses[keyof PostApiV1PrivateUsersResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
