"""Fix datetime error.

Revision ID: 00256652a84e
Revises: fbdd5b8eb59b
Create Date: 2025-09-17 12:49:00.910675

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00256652a84e'
down_revision = 'fbdd5b8eb59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
