"""Add score_percentage to QuizSession model.

Revision ID: 0622fd09b3a5
Revises: 83175d7579eb
Create Date: 2025-09-30 13:34:28.133974

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0622fd09b3a5'
down_revision = '83175d7579eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizsession', sa.Column('score_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizsession', 'score_percentage')
    # ### end Alembic commands ###
