"""Fix delete document error.

Revision ID: 10368f38610b
Revises: b5370243d0bc
Create Date: 2025-10-02 07:06:36.831373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '10368f38610b'
down_revision = 'b5370243d0bc'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'chat' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('chat',
            sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
            sa.Column('is_system', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('course_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.drop_constraint(op.f('quizattempt_quiz_id_fkey'), 'quizattempt', type_='foreignkey')
        op.create_foreign_key(None, 'quizattempt', 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizattempt', type_='foreignkey')
    op.create_foreign_key(op.f('quizattempt_quiz_id_fkey'), 'quizattempt', 'quiz', ['quiz_id'], ['id'])
    op.drop_table('chat')
    # ### end Alembic commands ###
