"""Add loaders to QuizAttempt 3.

Revision ID: 10594e38957f
Revises: f3eb013c9e20
Create Date: 2025-10-01 13:15:23.174763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '10594e38957f'
down_revision = 'f3eb013c9e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
