"""Add created and updated time columns in course and document models

Revision ID: 177fc617fc0b
Revises: 9edab5efe2e4
Create Date: 2025-09-23 08:46:17.677184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '177fc617fc0b'
down_revision = '9edab5efe2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'chat' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('chat',
            sa.Column('message', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
            sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
            sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('chat_course_id_fkey'), ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name=op.f('chat_pkey'))
        )
    # ### end Alembic commands ###
