"""Add chunk and questions models

Revision ID: 2dbd058f5a26
Revises: b93831eb9fa1
Create Date: 2025-09-25 14:21:37.876403

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2dbd058f5a26'
down_revision = 'b93831eb9fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
