"""Update the quiz_ids_json type

Revision ID: 2ffc50a3ceac
Revises: e6d25325d316
Create Date: 2025-09-29 15:58:58.532098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ffc50a3ceac'
down_revision = 'e6d25325d316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
