"""add new fields to course & document

Revision ID: 39944de728d4
Revises: e2412789c190
Create Date: 2025-09-22 12:54:08.913612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '39944de728d4'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('course', sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_course_created_at'), 'course', ['created_at'], unique=False)
    op.create_index(op.f('ix_course_owner_id'), 'course', ['owner_id'], unique=False)
    op.create_index(op.f('ix_course_uploaded_at'), 'course', ['uploaded_at'], unique=False)
    op.add_column('document', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'created_at')
    op.drop_index(op.f('ix_course_uploaded_at'), table_name='course')
    op.drop_index(op.f('ix_course_owner_id'), table_name='course')
    op.drop_index(op.f('ix_course_created_at'), table_name='course')
    op.drop_column('course', 'uploaded_at')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
