"""Fix typo in the course model.

Revision ID: 6030c89bf493
Revises: 177fc617fc0b
Create Date: 2025-09-23 10:02:34.553280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6030c89bf493'
down_revision = '177fc617fc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_course_uploaded_at'), table_name='course')
    op.create_index(op.f('ix_course_updated_at'), 'course', ['updated_at'], unique=False)
    op.drop_column('course', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_course_updated_at'), table_name='course')
    op.create_index(op.f('ix_course_uploaded_at'), 'course', ['uploaded_at'], unique=False)
    op.drop_column('course', 'updated_at')
    # ### end Alembic commands ###
