"""Default score percentage to zero

Revision ID: 6f9f908ab61d
Revises: 22a57877856f
Create Date: 2025-09-30 15:22:50.791401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f9f908ab61d'
down_revision = '22a57877856f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
