"""Fix quiz model.

Revision ID: 7e9bed2ef458
Revises: da0d62c46d33
Create Date: 2025-09-27 19:40:16.211723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e9bed2ef458'
down_revision = 'da0d62c46d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
