"""Rename from question to quiz.

Revision ID: 89c6ad1d0dc9
Revises: 3aab22ffba62
Create Date: 2025-09-26 19:32:14.169077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89c6ad1d0dc9'
down_revision = '3aab22ffba62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quiz_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distraction_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distraction_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distraction_3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    # sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', 'ALL', name='difficultylevel'), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distraction_1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distraction_2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distraction_3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('difficulty_level', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', 'EXPERT', 'ALL', name='difficultylevel'), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('question_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_pkey'))
    )
    op.drop_table('quiz')
    # ### end Alembic commands ###
