"""Add loaders to QuizAttempt 1.

Revision ID: 9c2387b5e3c7
Revises: f7c7ca6c61b5
Create Date: 2025-10-01 13:05:23.606634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c2387b5e3c7'
down_revision = 'f7c7ca6c61b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
