"""Add cascade delete to documents relationship

Revision ID: b93831eb9fa1
Revises: 373edea4505d
Create Date: 2025-09-23 16:18:57.084526

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b93831eb9fa1'
down_revision = '373edea4505d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
