"""Add quizzes tracking mechanism.

Revision ID: cba00d41de1b
Revises: 7e9bed2ef458
Create Date: 2025-09-28 20:08:56.051928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import expression # 👈 Import expression for server_default

# revision identifiers, used by Alembic.
revision = 'cba00d41de1b'
down_revision = '7e9bed2ef458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. quiz_ids_json: Add with temporary default ('[]')
    op.add_column(
        'quizsession',
        sa.Column(
            'quiz_ids_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]'
        )
    )
    # 2. updated_at: Add with server default and NOT NULL
    # This column is safe because the server_default provides a value for existing rows.
    op.add_column(
        'quizsession',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False
        )
    )

    # 3. is_completed: FIX for NotNullViolation
    # A. Add column with a temporary default value (False) for existing rows.
    op.add_column(
        'quizsession',
        sa.Column(
            'is_completed',
            sa.Boolean(),
            nullable=False, # We still want NOT NULL
            server_default=expression.false() # 👈 TEMPORARY DEFAULT for existing rows
        )
    )

    # 4. Remove Temporary Server Defaults
    # This allows SQLModel/Python defaults to take over for future insertions.

    op.alter_column('quizsession', 'quiz_ids_json', server_default=None, nullable=False)
    op.alter_column('quizsession', 'is_completed', server_default=None, nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizsession', 'is_completed')
    op.drop_column('quizsession', 'updated_at')
    op.drop_column('quizsession', 'quiz_ids_json')
    # ### end Alembic commands ###
