"""Add loaders to QuizAttempt 2.

Revision ID: f3eb013c9e20
Revises: 9c2387b5e3c7
Create Date: 2025-10-01 13:09:28.569835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3eb013c9e20'
down_revision = '9c2387b5e3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
