"""Add loaders to QuizAttempt.

Revision ID: f7c7ca6c61b5
Revises: 6f9f908ab61d
Create Date: 2025-10-01 13:00:31.838790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7c7ca6c61b5'
down_revision = '6f9f908ab61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
